// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqarlsowzmqptmufpxma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxYXJsc293em1xcHRtdWZweG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MjU2MjYsImV4cCI6MjA3MjAwMTYyNn0.v4PC86Wydj6nyKe0DEwsqy76Tyi0DkaGqFRrYaBVdps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});